### ISSUE TITLE
`numerous init` adds a sequence of characters at the end of requirements.txt

### ISSUE THREAD

**Issue by dk-teknologisk-pde** [numerous-com/numerous-sdk#37]
Right after I run `numerous init` to initialize my app, the following sequence of characters appears at the end of the _requirements.txt_ file: 瀊湡汥
![image](https://github.com/user-attachments/assets/80e4994c-1cf7-48d2-8e61-c1b8ba5b560e)
It then causes a problem when deploying the app at the `Build Step 4/7 : Runn pip install -r /app/requirements.txt`.
The solution to deploy the app anyway is to manually remove these characters before running `numerous deploy`, but I thought it was not an intended behavior.

**Comment by jfeodor** [comment]
Thanks for reporting this issue!

We will look into it! I have a couple of questions:

1. What operating system are you using?
2. Can you attach a copy of the `requirements.txt` file with the characters added by `numerous init` to a comment in the issue?

/Jens

**Comment by jfeodor** [comment]
And also:

3. What encoding is the file opened with in your editor? It looks like you are using VSCode or something related to that - in the image below I have highlighted the panel in the UI which displays the encoding; in my case it is UTF-8.

![image](https://github.com/user-attachments/assets/d64a41b7-19c9-488e-8e8a-e9293617c981)

**Comment by dk-teknologisk-pde** [comment]
1. I am using Windows 10 Enterprise (Version 22H2)
2. [requirements.txt](https://github.com/user-attachments/files/17203373/requirements.txt)
3. The encoding is UTF-16 LE, which might be a reason for the problem. I generated the _requirements.txt_ using the command `pip freeze > requirements.txt`.

**Comment by jfeodor** [comment]
Thanks for your response!

I believe that powershell by default creates UTF-16 encoded files when piping output, which could explain how the file was encoded that way initially.

We will look into if we can better support UTF-16 in the initialization of new apps. :)

**Comment by jfeodor** [comment]
We are working on a change that will attempt to detect the encoding of the requirements file from among a set of common encodings, inspired by the decoding implemented in pip: https://github.com/pypa/pip/blob/main/src/pip/_internal/utils/encoding.py

**Comment by jfeodor** [comment]
And for further input, the extra characters added were simply the characters for `<linefeed>panel` added onto the `utf-16-le` data as plain `utf-8` (basically `ascii`) characters.

When your editor then reinterpreted the data, the added `utf-8` bytes got interpreted as `utf-16-le`, e.g. `"<linefeed>p"` in `utf-8` is the byte sequence `0x0a 0x70`, and `utf-16` can contain that entirely as the [codepoint for 瀊](https://www.compart.com/en/unicode/U+700A).

And the reason why anything was added at all is that the CLI looked for `panel` in the requirements data as `utf-8`, and of course did not find anything and thus re-added the pre-existing dependency. :smile:

**Comment by dk-teknologisk-pde** [comment]
Thanks for the explanation!

**Comment by jfeodor** [comment]
Version 0.23.1 has been released which should contain a fix for this issue. Please let us know if the issue persists :smile:
